# Simple LSTM

In [ ]:
##########################################################################################################
# SOME REFERENCES: https://medium.com/towards-data-science/whats-happening-in-my-lstm-layer-dd8110ecc52f #
##########################################################################################################

#################################################################################
# SOME REFERENCES: https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html #
#################################################################################

import torch
import torch.nn as nn

""" Class for a simple LSTM. """
class MyLSTM(nn.Module):
    """ Initialize configurations. """
    def __init__(self, input_size, hidden_size, num_layers, output_size, device, bidirectional=False):
        super(MyLSTM, self).__init__()
        # number of features of x
        self.input_size = input_size
        # number of features in the hidden state h
        self.hidden_size = hidden_size
        # number of recurrent layers
        self.num_layers = num_layers
        # number of output neurons of linear layer
        self.output_size = output_size
        # D parameter
        self.directions = 2 if bidirectional else 1
        # device
        self.device = device

        # lstm-architecture:
        self.lstm = nn.LSTM(input_size=input_size,
                            hidden_size=hidden_size,
                            num_layers=num_layers,
                            batch_first=True).to(device)

        # linear-layer
        self.fc1 = nn.Sequential(
            # we take the last cell outputs with shape (batch_size, D * hidden_size)
            nn.Linear(self.directions * self.hidden_size, self.output_size),
            # nn.ReLU(inplace=True)
        )

    """ Method used to define the forward pass of the input through the network during the training. """
    def forward(self, x):
        # input shape (batch_size, sequence_length, number_features) when batch_first=True
        batch_size = x.size(0)
        # (D ∗ num_layers, batch_size, hidden_size)
        h_0 = torch.zeros((self.directions * self.num_layers,
                           batch_size, self.hidden_size)).to(self.device)
        c_0 = torch.zeros((self.directions * self.num_layers,
                           batch_size, self.hidden_size)).to(self.device)

        # output-shape (batch_size, sequence_lenght, D * hidden_size)
        # h_n-shape (D * num_layers, batch_size, hidden_size)
        # c_n-shape (D * num_layers, batch_size, hidden_size)
        output, (h_n, c_n) = self.lstm(x, (h_0, c_0))

        print("\n", output.shape, h_n.shape, c_n.shape)
        print("\n", output, "\n\n", h_n, "\n\n", c_n)

        # takes the last cell outputs of all batches
        print("\nlast cell outputs shape: \n", output[:, -1, :].shape)
        print("\nlast cell outputs: \n", output[:, -1, :])

        lin_out = self.fc1(output[:, -1, :])

        print(f"\nlin-out-shape: {lin_out}")


""" Runs the simulation. """
if __name__ == "__main__":

    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    print(f"device: {device}")

    x = torch.randn((2, 6, 6))
    print(f"\nx-shape: {x.shape}")

    num_features = int(x.shape[2])

    model = MyLSTM(input_size=num_features,
                   hidden_size=6,
                   num_layers=1,
                   output_size=1,
                   device=device)

    out = model(x)

##################
# output example #
##################

# device: cpu

# x-shape: torch.Size([2, 6, 6])

# torch.Size([2, 6, 6]) torch.Size([1, 2, 6]) torch.Size([1, 2, 6])

# tensor([[[ 0.0670,  0.0398,  0.2406, -0.2882,  0.0184, -0.1168],
#          [-0.0813,  0.2598,  0.3303, -0.1901,  0.1681, -0.1573],
#          [-0.0013,  0.0993,  0.3154, -0.2576,  0.2350, -0.2473],
#          [ 0.1037,  0.0869,  0.3699, -0.1835,  0.0433, -0.3695],
#          [ 0.1005,  0.2060,  0.3575, -0.1126,  0.0005, -0.3399],
#          [ 0.0111,  0.1685,  0.4348, -0.2917,  0.1025, -0.2308]],

#         [[ 0.2161, -0.0216,  0.1619, -0.0560, -0.1214, -0.2652],
#          [ 0.1342,  0.1155,  0.3858, -0.1652, -0.1072, -0.2497],
#          [-0.0412,  0.2684,  0.1980, -0.1152,  0.2417, -0.0435],
#          [-0.4885,  0.4563, -0.0637, -0.1715,  0.2013,  0.0407],
#          [-0.1746,  0.2125,  0.0317, -0.2900,  0.3504, -0.0428],
#          [-0.3115,  0.3664, -0.0838, -0.2712,  0.2742, -0.0829]]],
#        grad_fn=<TransposeBackward0>)

# tensor([[[ 0.0111,  0.1685,  0.4348, -0.2917,  0.1025, -0.2308],
#          [-0.3115,  0.3664, -0.0838, -0.2712,  0.2742, -0.0829]]],
#        grad_fn=<StackBackward0>)

# tensor([[[ 0.0251,  0.3550,  0.9562, -0.6240,  0.2229, -0.6161],
#          [-0.4754,  0.7592, -0.2685, -0.7482,  0.9308, -0.2028]]],
#        grad_fn=<StackBackward0>)

# last cell outputs shape: torch.Size([2, 6])

# last cell outputs:
# tensor([[ 0.0111,  0.1685,  0.4348, -0.2917,  0.1025, -0.2308],
#         [-0.3115,  0.3664, -0.0838, -0.2712,  0.2742, -0.0829]],
#        grad_fn=<SliceBackward0>)

# lin-out-shape:
# tensor([[0.2285],
#         [0.3122]], grad_fn=<ReluBackward0>)


# Autoencoder LSTM

In [1]:
##########################################################################################################
# SOME REFERENCES: https://medium.com/towards-data-science/whats-happening-in-my-lstm-layer-dd8110ecc52f #
##########################################################################################################

#################################################################################
# SOME REFERENCES: https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html #
#################################################################################

import torch
import torch.nn as nn

""" Class form LSTM in Autoencoder configuration. """
class MyAutoEncLSTM(nn.Module):
    """ Initialize configurations. """
    def __init__(self, input_size, hidden_size, embedding_dim, num_layers, device, bidirectional=False):
        super(MyAutoEncLSTM, self).__init__()
        # the number of expected features in the input x
        self.input_size = input_size
        # the number of features in the hidden state h
        self.hidden_size = hidden_size
        # the hidden-size of the last encoder layer
        self.embedding_dim = embedding_dim
        # number of recurrent layers
        self.num_layers = num_layers
        # if true becomes a bidirectional LSTM
        D = 2 if bidirectional else 1
        self.directions = D
        # device where to put tensors
        self.device = device

        # lstm-architecture
        self.lstm_encoder1 = nn.LSTM(input_size=input_size,
                                     hidden_size=hidden_size,
                                     num_layers=num_layers,
                                     batch_first=True)
        # lstm-architecture
        self.lstm_encoder2 = nn.LSTM(input_size=D*hidden_size,
                                     hidden_size=embedding_dim,
                                     num_layers=num_layers,
                                     batch_first=True)
        # # lstm-architecture
        # self.lstm_decoder1 = nn.LSTM(input_size=input_size,
        #                              hidden_size=hidden_size,
        #                              num_layers=num_layers,
        #                              batch_first=True)
        # # lstm-architecture
        # self.lstm_decoder2 = nn.LSTM(input_size=input_size,
        #                              hidden_size=hidden_size,
        #                              num_layers=num_layers,
        #                              batch_first=True)

    """ Method used to define the forward pass of the input through the network during the training. """
    def forward(self, x):
        # input shape (batch_size, sequence_length, number_features) when batch_first=True

        # output-shape (batch_size, sequence_lenght, D * hidden_size)
        # h_n-shape (D * num_layers, batch_size, hidden_size)
        # c_n-shape (D * num_layers, batch_size, hidden_size)
        enc1_output, (_, _) = self.lstm_encoder1(x)

        print(f"\nenc1-output-shape: \n{enc1_output.shape}")
        print(f"\nenc1-output: \n{enc1_output}")

        enc2_output, (hidden_n, _) = self.lstm_encoder2(enc1_output)

        print(f"\nenc2-output-shape: \n{enc2_output.shape}")
        print(f"\nenc2-output: \n{enc2_output}")
        print(f"\nhidden_n-shape: \n{hidden_n.shape}")
        print(f"\nhidden_n: \n{hidden_n}")

        # cosa prendo: ?
        # prendo enc2_output oppure hidden_n ? --> l'architettura di rete cambia
        # volgio un output di encoder_2 di tipo flatten per la classificazione successiva ?
        
        # va bene ?
        # input [bs, 5, 18]
        # enc1-out [bs, 5, 9]
        # enc2-out [bs, 5, 3]
        # dec1-out [bs, 5, 9]
        # dec2-out [bs, 5, 18] ???

        # poi classif: ?
        # con criterion = binary-crossentropy
        # input [bs, 5, 18]
        # enc1-out [bs, 5, 9]
        # flatten [bs, 5 * 9] = [bs, 45]
        # fc1-out [45, 10]
        # fc2-out [10, 1]
        # sigmoide


""" Runs the simulation. """
if __name__ == "__main__":
    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    print(f"\ndevice: \n{device}")

    batch_size = 2
    seq_len = 5
    num_features = 18
    hidden_size = 9
    embedding_dim = 3
    num_layers = 1    
    x = torch.rand((batch_size, seq_len, num_features))

    print(f"\ninput-shape: \n{x.shape}")
    print(f"\ninput: \n{x}")

    # model definition
    model = MyAutoEncLSTM(input_size=num_features,
                          hidden_size=hidden_size,
                          embedding_dim=embedding_dim,
                          num_layers=num_layers,
                          device=device)

    # model output
    output = model(x)



device: 
cpu

input-shape: 
torch.Size([2, 5, 18])

input: 
tensor([[[0.7559, 0.6392, 0.0092, 0.6452, 0.1449, 0.6909, 0.0577, 0.2998,
          0.7970, 0.2855, 0.5392, 0.8484, 0.4107, 0.9068, 0.5477, 0.4698,
          0.3176, 0.5685],
         [0.8637, 0.8399, 0.7292, 0.2000, 0.8625, 0.0156, 0.0622, 0.5205,
          0.6573, 0.9495, 0.6972, 0.2059, 0.5491, 0.2809, 0.8860, 0.6234,
          0.1517, 0.2491],
         [0.8693, 0.6708, 0.3647, 0.0499, 0.7697, 0.6454, 0.2044, 0.4120,
          0.4847, 0.1272, 0.9818, 0.1897, 0.9270, 0.9540, 0.9138, 0.3410,
          0.0813, 0.4835],
         [0.5663, 0.2518, 0.0441, 0.8284, 0.2990, 0.0440, 0.7476, 0.7062,
          0.7127, 0.4158, 0.3692, 0.9686, 0.9411, 0.8914, 0.8552, 0.9373,
          0.8465, 0.4164],
         [0.5319, 0.7169, 0.0394, 0.3653, 0.2439, 0.6420, 0.2193, 0.9187,
          0.9993, 0.5404, 0.3560, 0.0227, 0.3102, 0.8633, 0.2731, 0.7243,
          0.8787, 0.3147]],

        [[0.7206, 0.8235, 0.7044, 0.4646, 0.4504, 0.4005, 0.06